name: Spellcheck Action
on: push

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      # The checkout step
      - uses: actions/checkout@master
      - uses: rojopolis/spellcheck-github-actions@0.14.0
        name: Spellcheck
        with:
          source_files: README.md CHANGELOG.md notes/Notes.md
          task_name: Markdown
        matrix:
          - name: Markdown
            aspell:
              lang: en
            dictionary:
              encoding: utf-8
            pipeline:
              - pyspelling.filters.markdown:
              - pyspelling.filters.html:
                comments: false
                ignores:
                  - code
                  - pre
            sources:
              - "**/*.md"
            default_encoding: utf-8
